### ISSUE TITLE
Define FollowUp Actions for all Contacts in "CONTACTS MANAGEMENT"

### ISSUE THREAD

**Issue by serapath** [RefugeesWork/organization#11]
Check all contacts in: https://waffle.io/RefugeesWork/organization/cards/5771718e3ca69e5201af1c8e

1. If nothing can be currently done for certain contacts, then a `waiting/onHold` issue should be created describing what's currently blocking it or what we wait for and until when the contact needs to be revisited later

2. Every issue, whether it's a `waiting/onHold` or a `Ready/Next` one, needs to be linked somewhere as a task into the OVERVIEW `Mission` issues

**Comment by ninabreznik** [comment]
@serapath Please, add status (waiting or ready) also for people you are in touch https://waffle.io/RefugeesWork/organization/cards/5771718e3ca69e5201af1c8e and please add the ones that are not in the system yet (Volunteer etc.)
