### ISSUE TITLE
Dissolve Inspirational Links

### ISSUE THREAD

**Issue by serapath** [RefugeesWork/organization#6]
# Link Collection
~~Post any related links below :-)~~

This will soon be removed.
We will post links on the gitter chat instead.
If we think a link is relevant to our mission or a related task, it should be added there instead :-)

**Comment by serapath** [comment]
elektronische Steuererklärung
* https://www.berlin.de/sen/finanzen/steuern/informationen-fuer-steuerzahler-/elektronische-steuererklaerung/artikel.11569.php

**Comment by ninabreznik** [comment]
Info videos:
* https://www.facebook.com/yallahdeutschland
* https://www.facebook.com/glsgermanlifestyle
* https://www.facebook.com/4andhalf/
* https://www.facebook.com/WDRforyou
