### ISSUE TITLE
27.6.2016 - OKF, Tempelhofer Ufer (Meeting1)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/organization#7]
## 27.6.2016 - OKF, Tempelhofer Ufer

* reviewed the workshop a bit
* talked about survey
* talked about what information do newcomers need (regarding work - what can they do in each stage of their application process)

**Comment by ninabreznik** [comment]
## 26.6.2016 - OKF, Tempelhofer Ufer

* reviewed the workshop a bit
* talked about survey
* talked about what information do newcomers need (regarding work - what can they do in each stage of their application process)

**Comment by serapath** [comment]
## 04.7.2016 - OKF, Tempelhofer Ufer

* ...
